### ISSUE TITLE
社团里面几个人模拟器测试中触发的log(崩溃了)

### ISSUE THREAD

**Issue by naloder** [xausky/UnityModManager#13]
03-18 22:56:36.832  2765  2765 E AndroidRuntime: FATAL EXCEPTION: main
03-18 22:56:36.832  2765  2765 E AndroidRuntime: Process: io.github.xausky.unitymodmanager, PID: 2765
03-18 22:56:36.832  2765  2765 E AndroidRuntime: com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.lody.virtual.client.env.VirtualRuntime.crash(VirtualRuntime.java:61)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.lody.virtual.client.core.VirtualCore.getInstalledAppInfo(VirtualCore.java:520)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at io.github.xausky.unitymodmanager.fragment.HomeFragment.clientUpdate(HomeFragment.java:154)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at io.github.xausky.unitymodmanager.fragment.HomeFragment.onCreateView(HomeFragment.java:103)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:1700)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:684)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:733)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:136)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5089)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:515)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: Caused by: android.os.DeadObjectException
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at android.os.BinderProxy.transact(Native Method)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.lody.virtual.helper.ipcbus.IPCMethod.callRemote(IPCMethod.java:107)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.lody.virtual.helper.ipcbus.IPCInvocationBridge.invoke(IPCInvocationBridge.java:27)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at $Proxy1.getInstalledAppInfo(Native Method)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	at com.lody.virtual.client.core.VirtualCore.getInstalledAppInfo(VirtualCore.java:518)
03-18 22:56:36.832  2765  2765 E AndroidRuntime: 	... 17 more

**Comment by naloder** [comment]
看看啥原因_(:з」∠)_

**Comment by xausky** [comment]
@naloder 我用最新版MuMu模拟器进行了一下测试，没有出现崩溃情况，可以具体说明一下崩溃的情形么，比如什么模拟器，什么版本的管理器，进行什么操作时候崩溃。

**Comment by naloder** [comment]
是MUMU模拟器，最新版，最新版管理器，游戏进入某一个关卡时候闪退，昨天自排查发现是一个mod导致的。。需要吧mod发过来看看吗？

**Comment by xausky** [comment]
好，还有说明一下是哪一关卡。

**Comment by naloder** [comment]
@xausky 午夜的访客-困难-月色

**Comment by xausky** [comment]
可以把模组也上传一下么，直接附件上传应该可以

**Comment by naloder** [comment]
武器双枪…精卫之羽.zip
https://pan.baidu.com/s/1j7ikyvJKt7oH0hHW6dkofQ

**Comment by xausky** [comment]
我测试使用传统的模组安装方法（VAMod + xplore）也会闪退，应该是模组的问题了，不是管理器能够解决的。
