### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by naloder** [xausky/UnityModManager#14]
在某些情况下触发打完mod以后管理器闪退报错，没有影响游戏体验但是却没有保存已经打mod的情况，重新进入管理器原来打勾的变成未打勾，如果有需要可以提供log

**Comment by naloder** [comment]
ps:正常主界面点右上角直接进入游戏mod已经是被打入状态以后的了，但是模组那边没有打勾

**Comment by naloder** [comment]
模组大量多选操作偶发崩溃，勾选显示问题在清除数据重装底包和mod后仍然复现

**Comment by naloder** [comment]
打龙出现闪退，活动关龙之秘宝

**Comment by xausky** [comment]
setRecyclerView 的 NullPointerException是在什么时候会触发，是必定触发的么，新版本触发最多的就是这个bug了

**Comment by naloder** [comment]
@xausky 新版本我是在打mod打到一定进度，在1.15G(打完理论1.3g+作用)管理器发生闪退，

**Comment by xausky** [comment]
在我这里无法重现这个BUG，先关闭了。
