### ISSUE TITLE
关于氪金

### ISSUE THREAD

**Issue by melxman** [xausky/UnityModManager#15]
不知道为什么，崩崩崩在我手机里只认阿宝，不认WX，选择WX支付后，蹦不出关联。程序可见里默认已经有了WX

**Comment by melxman** [comment]
在后台也不行，可以明显的听到按了付款按钮后，有的音效，也能发现有跳转的闪动，但是实际还是保持在了游戏本体中，没有变化

**Comment by xausky** [comment]
应该是可以的，不行的话还是去原版客户端氪吧。
