### ISSUE TITLE
一加5T兼容性

### ISSUE THREAD

**Issue by yangdong625** [xausky/UnityModManager#16]
在一加5T上无法进入游戏，所有权限已开。

**Comment by naloder** [comment]
最好可以提供log_(:з」∠)_

**Comment by xausky** [comment]
是在那一步出现问题的，点击手柄图标出现对话框没有。

**Comment by yangdong625** [comment]
就是OPPO服的登录是会先跳到一个“游戏中心”的界面，完成登陆后再跳回游戏界面，现在的情况是界面会在游戏和这个“游戏中心”的界面不断跳，登不上去……

**Comment by xausky** [comment]
你这个应该是OPPO服的兼容性，和一加5T没有太大关系。

**Comment by asunaCC** [comment]
我的也是一加五t，然后是用的b服，每次都是在添加模组后进入游戏界面就直接闪退

**Comment by asunaCC** [comment]
请问该怎么解决这个问题啊？

**Comment by asunaCC** [comment]
所有权限都给了

**Comment by xausky** [comment]
具体是哪个游戏界面

**Comment by asunaCC** [comment]
就是加载游戏配置时，大概加载十分之三左右管理器就直接

**Comment by asunaCC** [comment]
闪退

**Comment by naloder** [comment]
@asunaCC 在应用组件或者外部可见性加入b站了吗

**Comment by xausky** [comment]
你用了些什么模组，现在好像有个模组会导致闪退。

**Comment by xausky** [comment]
他这个不是登录问题和而且b服不需要加附加组件。@naloder

**Comment by asunaCC** [comment]
都加了

**Comment by asunaCC** [comment]
都加了

**Comment by xausky** [comment]
模组列表截图给我看看

**Comment by asunaCC** [comment]
怎么上传图片啊？・_・?

**Comment by asunaCC** [comment]
我发你邮箱了

**Comment by xausky** [comment]
好像是皇家手弩吧，不行你多试试，反正是某个模组的问题
