### ISSUE TITLE
miui这今天更新后无法启动游戏了

### ISSUE THREAD

**Issue by LexingtonHX** [xausky/UnityModManager#17]
似乎是miui这次更新后不支持虚拟环境形式了，以前是改动过system后miui更新会变成更新完整包，没改动system则可以.增量包升级
现在只是装了unitymod管理器并导入崩崩崩后，就导致了miui需要更新完整包，并且更新后管理器无法启动游戏了，一直报错

系统版本miui9 8.4.12

**Comment by LexingtonHX** [comment]
我这里还有错误报告的log，如果有需要的话我会发出来

**Comment by naloder** [comment]
首先管理器改动的是data分区目录下的那个虚拟环境里面的安装包，并未改动system，有没有可能是因为root了?第二如果无法开始游戏重新导入安装包试试?

**Comment by LexingtonHX** [comment]
尝试过重新导入了，无mod情况下都一直报错FC

**Comment by xausky** [comment]
有错误日志的话发出来看看

**Comment by LexingtonHX** [comment]
可以留下邮箱吗，这里我不知道怎么发，我发你邮箱去吧

**Comment by xausky** [comment]
xausky@163.com

**Comment by LexingtonHX** [comment]
已发送

**Comment by xausky** [comment]
看日志好像是VA的问题，应该和系统版本之类有关，但是我也不知道如何解决。
