### ISSUE TITLE
能不能做一个不含虚拟环境，单纯是xposed模块的branch啊。。。

### ISSUE THREAD

**Issue by Zxilly** [xausky/UnityModManager#18]
%dalao

**Comment by naloder** [comment]
xp模块实现这样。。太夸张了吧。。(●—●)。。我觉得很难吧

**Comment by xausky** [comment]
xp模块实现是不可能了，这辈子都不可能，root模式倒是可以考虑

**Comment by zxy1001** [comment]
我原来试过hook资源。。。但是莫名其妙的会崩溃。。。

**Comment by xausky** [comment]
关键是有xp框架的还是少数，基本上不考虑开发

**Comment by naloder** [comment]
@zxy1001 对1G+的包进行hook本来就不好保持稳定性吧_(:з」∠)_
