### ISSUE TITLE
请问是否可以支持谷歌服务

### ISSUE THREAD

**Issue by makoto1995** [xausky/UnityModManager#19]
目前日服无法使用谷歌登陆，很紧急

**Comment by naloder** [comment]
在外部应用可见性或者内部组件添加google服务，google框架，google游戏这三个试试?

**Comment by naloder** [comment]
添加内部应用组件

**Comment by xausky** [comment]
https://github.com/asLody/VirtualApp/blob/master/CHINESE.md
VA引擎在这里说了：在google service新版本，存在兼容适配问题，暂时屏蔽
所以我也没办法。
