### ISSUE TITLE
关于mod安装替换的问题

### ISSUE THREAD

**Issue by Moe-New** [xausky/UnityModManager#20]
非常感谢dalao开发了此工具~
 
现在我有一个替换“月光默认皮肤”的mod，我想设定为替换”月光暗噬皮肤“，这个功能可以在该工具内做得到吗？

感谢！

**Comment by naloder** [comment]
不能吧，除非从id层面改，模组管理器无法实现吧。。除非管理器能实现替换id就当我没说

**Comment by Zxilly** [comment]
定位月光另一个皮肤的文件，改下文件名就好，但要是骨骼不一样就不行（然而那并不可能

**Comment by xausky** [comment]
这个不是管理器能做的，得靠做模组的大佬改。
