### ISSUE TITLE
点击右上角手柄图标，运行一段时间程序停止工作

### ISSUE THREAD

**Issue by s297002170** [xausky/UnityModManager#21]
机型：三星galaxy s9  安卓版本：8.0.0

**Comment by xausky** [comment]
emm，应该是VirtualApp对S9兼容的问题，我无法解决，现在VA开源版又基本不更新，只能等一波官方全面使用资源热更新，像九游服那样，这样就可以脱离VA了。

**Comment by naloder** [comment]
@xausky 然后有更黑科技做法?!

**Comment by xausky** [comment]
如果官方后续全部改为像九游服那样，那就好办了，只需要修改外部存储的数据就行，不需要root也不需要va，兼容性可以非常好，不过据说如果那样iOS服的魔改不越狱就完全没法搞了。
