### ISSUE TITLE
APP需要更新时的卡死问题

### ISSUE THREAD

**Issue by XnzkiONA** [xausky/UnityModManager#22]
(在需要更新的情况下)
进入unity模组管理器后，点击右上角游戏按钮，弹出升级窗口，取消更新，APP就会卡死

**Comment by xausky** [comment]
取消更新卡死应该是少数问题，建议自行获取最新安装包更新。

**Comment by XnzkiONA** [comment]
点了取消更新，然后 软件无法打开游戏，一直卡在“正在操作”的界面
