### ISSUE TITLE
[台服] 執行遊戲後一陣子，會出現錯誤訊息

### ISSUE THREAD

**Issue by ezken** [xausky/UnityModManager#23]
裝置： OnePlus 5T
系統： OxygenOS 5.1.1 (Android 8.1.0)
APK版本： bh3_0503
APK來源： http://www.tw.bh3.com
APK下載： http://www.mygame.com.tw/MyGameAD/Accept.aspx?P=EFPWR646WA&S=QUNRMMN7HY

感謝作者辛勤的開發，造福我們可以玩賞各種MOD。 <(_ _)>

在進入遊戲後，過了一小段時間，必然會跳出錯誤訊息。
如圖：
![screenshot_20180515-031353](https://user-images.githubusercontent.com/39298340/40111992-2b4856ca-5937-11e8-8f6e-b06e84e0738d.jpg)
> 備用的文字訊息：
> `uid=10125948`
> `vid=2.2.0_tw_mycard`
> `msg=AndroidJavaException: java.lang.IllegalStateException:`
> `Default FirebaseApp is not initialized in this process`
> `com.miHoYo.bh3twmycard. Make sure to call`
> `FirebaseApp.initializeApp(Context) first.`

在UnityModManager v2.2.0的時候，按下繼續遊戲的話，則畫面會卡住。
而最近更新的UnityModManager v2.3.0，在按下繼續遊戲後，依然可以進行遊戲。

目前並不影響遊戲進行，MOD也能正常玩賞，僅作回報參考。
再次感謝作者～ <(_ _)>

**Comment by xausky** [comment]
既然不影响的话就先不搞了，应该是VirtualApp的问题，我不好修复。
