### ISSUE TITLE
Not applicable for games using obb data ?

### ISSUE THREAD

**Issue by Miika2211** [xausky/UnityModManager#24]
I have tried applying your application to honkai impact 3 (崩坏3 server sea) but not successful because it uses data obb file
Please, Can you add functionality that applies to games use data obb files?
Thanks you very much

**Comment by xausky** [comment]
I downloaded the honkai impact 3 SEA server, which is version 2.0. This manager does not support version 2.0 now. You need to modify the mod to use it (although it is also very simple to modify), but you can find it for version 2.0. mod?
If it can't be found, although it's not very difficult to do it, I don't think it would make sense to support OBB.

**Comment by Miika2211** [comment]
Thanks for answering.
A few days ago, I have successfully combined apk and obb together.
I tried your app and was successful.
Thanks you very much.



And I have suggestions
please, Can you add English language to your app ?

**Comment by xausky** [comment]
I am willing to add English support to my application, but my English is very poor and can only be done through Google Translate.

**Comment by xausky** [comment]
Although you have merged apk and obb, I think it is better to support obb. I will add support for obb in the near future.

**Comment by Miika2211** [comment]
Thanks you very much

**Comment by xausky** [comment]
https://github.com/xausky/UnityModManager/releases/tag/v2.3.2-dev2

This version implements obb support and English interface support.
