### ISSUE TITLE
[台服] 部分裝置，Facebook登錄失敗

### ISSUE THREAD

**Issue by ezken** [xausky/UnityModManager#25]
感謝作者辛勤的開發，造福我們可以玩賞各種MOD。 <(_ _)>

台服的第三方登錄為Facebook，而部分裝置的環境，似乎會有不明原因的登錄失敗。

當沒有偵測到Facebook App時，台服的崩壞3rd會啟用網頁模式登錄，而偵測到有Facebook App時，則會透過Facebook App進行登錄。

部分裝置不論是**使用網頁模式登錄**，或是**透過附加組件安裝Facebook App**，都無法成功登錄。
即使單獨先在附加組件內的Facebook App進行登錄後，再進入遊戲進行第三方登錄，也依然會失敗。
蒐集畫面：
Samsung Galaxy Note 5
![53989](https://user-images.githubusercontent.com/39298340/40305880-0701da10-5d2f-11e8-9d27-4ae115253853.jpg)
![53991](https://user-images.githubusercontent.com/39298340/40305881-072a2808-5d2f-11e8-82ee-389e01cd56fe.jpg)
HTC U11
![screenshot_20180519-135823](https://user-images.githubusercontent.com/39298340/40305884-07a50550-5d2f-11e8-89fe-d492edfab5db.png)
![screenshot_20180519-140306](https://user-images.githubusercontent.com/39298340/40305885-07ce1076-5d2f-11e8-9320-111767600016.png)

＝＝＝＝＝＝＝＝＝＝測試環境＝＝＝＝＝＝＝＝＝＝
UnityModManager版本： 2.3.0
崩壞3rd.tw APK版本： bh3_0503
崩壞3rd.tw APK來源： http://www.tw.bh3.com
崩壞3rd.tw APK下載： http://www.mygame.com.tw/MyGameAD/Accept.aspx?P=EFPWR646WA&S=QUNRMMN7HY
附加組件使用Facebook Lite的APK來源： https://zh-tw.facebook.com/lite/
附加組件使用Facebook Lite的APK下載： https://scontent.ftpe7-4.fna.fbcdn.net/v/t58.10285-6/28174544_246047425945768_4011366349132529664_n.apk/facebook_lite_v94.0.0.8.182.apk?_nc_cat=0&oh=4f5e97969d5e781040ce0d44ae2d881c&oe=5B0541F6

已知登錄失敗裝置：
Samsung Galaxy Note 5 (Android 5.1.1)
Sony Xperia XZ (Android 8.0.0)
HTC U11 (Android 8.0.0)

已知登錄成功裝置：
OnePlus 5T (OxygenOS 5.1.1, Android 8.1.0)

**Comment by xausky** [comment]
这个我想是virtual app这个项目的问题，我已经在管理器暴露出这个库的所有接口，就是应用可见性和附加组件，更多的解决方案我也无能为力。

**Comment by ezken** [comment]
我再找機會，多借幾個裝置試試。

**Comment by melxman** [comment]
这个似乎和谷歌全家桶一个问题？我这边用谷歌登录就不行

**Comment by xausky** [comment]
这个问题应该和华为服一样，登陆的接口对客户端进行hash检查，这样的话可以尝试先登陆再安装模组，不行的话只能使用Root模式。

**Comment by ezken** [comment]
抱歉，之前工作太忙......
使用UnityModManager v2.6來測試Facebook登錄（不含附加組件），上述裝置依然會碰到一樣的問題。
但由於現在已支援使用miHoYo帳號登錄，所以能迴避這個問題了。
![screenshot_20181003-035538](https://user-images.githubusercontent.com/39298340/46437437-ed477700-c78d-11e8-9f79-507216e794d3.jpg)
