### ISSUE TITLE
应用宝服, QQ客户端会被指为非官方

### ISSUE THREAD

**Issue by DeXtmL** [xausky/UnityModManager#27]
登陆时，QQ会显示“该应用非官方正版应用。。。”错误代码100044，并且拒绝登陆。
如果把QQ加入附加模组则可以登陆，但登陆完成后返回崩3时闪退。

目前无有效进入游戏手段。。。 

崩崩崩2.3 , QQ v7.6.3.3565

**Comment by naloder** [comment]
请添加手机安卓版本

**Comment by xausky** [comment]
请参考这个视频P2操作，主要一定要保证QQ在附加组件而不是应用可见性。
https://www.bilibili.com/video/av24407757/
