### ISSUE TITLE
应用宝服新版QQ无法登陆

### ISSUE THREAD

**Issue by Harry124** [xausky/UnityModManager#28]
应用宝服崩坏三登陆QQ时一直在加载，无法正常登陆

**Comment by xausky** [comment]
参考这个视频的P2，https://www.bilibili.com/video/av24407757/
视频里面使用的QQ是最新版。

**Comment by Harry124** [comment]
大佬我每一步都是按照视频来的，但就是QQ一直在登陆中，而且有一些小伙伴有一样的问题。

**Comment by xausky** [comment]
那用旧版QQ可以？

**Comment by Harry124** [comment]
旧版没尝试过，我刚刚想用mod就出现了这种状况(T＿T)
会不会是手机的问题，我在用华为荣耀9。

**Comment by xausky** [comment]
尝试一下旧版QQ，有人反馈6.5版本可以

**Comment by Harry124** [comment]
能用了

**Comment by Harry124** [comment]
谢谢
