### ISSUE TITLE
B服登陆界面闪退，无法登陆

### ISSUE THREAD

**Issue by lastice** [xausky/UnityModManager#29]
手机是mix2s，系统是最新的miui10开发版内测，安卓8.0。在用模组管理器加载完B服apk后，打开的时候一加载到登陆界面就会直接退到模组管理器主页，登陆都登不了，从2.2到2.3.2都试过了，还是不行。

**Comment by naloder** [comment]
添加B站到侧栏的程序组件里面

**Comment by lastice** [comment]
emmm，还有一个小问题，就是在账户那里，输入兑换码的时候，一点输入框就闪退。之前miui9，模拟器都不会这样，感觉是miui10的锅。

**Comment by naloder** [comment]
@lastice 应该是内存占用过大或者内存机制类原因，尝试锁定输入法和模组管理器等，如果仍然闪退应该就是目前miui10的锅了吧(或许):joy:

**Comment by lastice** [comment]
试了一下，还是不行，以后就在模拟器上输兑换码算了

**Comment by xausky** [comment]
安卓8.1存在输入框闪退问题，而且B服的登陆不需要B站客户端吧，所以不需要加到附加组件，输入闪退问题我会尝试解决。

**Comment by lastice** [comment]
大佬是这样的，之前miui10没有添加B站客户端的时候，是在出现登陆界面的一瞬间就闪退到模组管理器主页，账号密码都输入不了，直接闪退。后来我按照上面那个老哥说的添加附加组件还是不行，最后是在应用可见性里添加的B站客户端，在进游戏登陆时就会提示是否用B站账号一键登录，就可以正常进游戏了。然后我的手机是安卓8.0，miui9的时候就一切正常，感觉miui10是不改了什么23333

**Comment by xausky** [comment]
可以用了就好
