### ISSUE TITLE
更改昵称，简介，填写兑换码等闪退

### ISSUE THREAD

**Issue by Ph4n7om** [xausky/UnityModManager#30]
如题，似乎点击左上角昵称进入个人信息之后，点击所有文本框都会使游戏立即闪退。游戏为崩3官服2.4版，模组管理器也为2.4版，但之前版本已有相同问题。手机为索尼XZ Premium，系统为官方8.0最新国际版，未root，无Xposed框架。提前谢谢了。

**Comment by xausky** [comment]
应该是安卓8.1吧，这个有bug，现在暂时无法解决

**Comment by Ph4n7om** [comment]
@xausky 不是8.1，确定是8.0。不过暂时无法解决那就等等也没什么。😁

**Comment by xausky** [comment]
有解决方法了，暂时关闭Android系统的自动填充服务，在安卓原版的操作为：设置->系统->语言和输入法->高级->自动填充服务（改为无即可）。

**Comment by Ph4n7om** [comment]
@xausky 谢谢，我这就去试试。另外我想问一下，对于安卓官服来说，设置怎样更改最好呢？

**Comment by xausky** [comment]
修改方式选择虚拟环境，补丁支持都不需要OBB和持久化都不需要。

**Comment by xausky** [comment]
测试好了可以给个反馈么

**Comment by Ph4n7om** [comment]
@xausky 测试完了，不闪退了😊
