### ISSUE TITLE
使用管理器启动崩坏3，偶尔在按下近期应用键后，显示多个崩3预览窗口

### ISSUE THREAD

**Issue by Ph4n7om** [xausky/UnityModManager#31]
如题，昨天根据你的回复，关掉设置中两种补丁支持的选项后发现的，不知是否有必然联系。多个窗口中若点按可能是“错误”的窗口会造成闪退。另外，apk资源修改方式哪种效率最高？官服也能用“不修改”模式吗？

**Comment by xausky** [comment]
官方的资源在apk里面，必须选择一种修改方式，多个预览窗口可以给个截图看看么

**Comment by Ph4n7om** [comment]
@xausky 之前我选择的是“虚拟环境模式”，在关掉持久化Unity资源补丁支持，并出现两三次这个问题后，我现在尝试的是“不修改”，同时重新把持久化Unity资源补丁支持打开。多个重复预览窗口问题复现得等等，我之前没截图。

**Comment by Ph4n7om** [comment]
@xausky 说曹操曹操到，问题出现了。
![screenshot_20180623-183118](https://user-images.githubusercontent.com/28192782/41808687-e5328b4c-7713-11e8-9198-56010b561ac2.png)

**Comment by Ph4n7om** [comment]
@xausky 貌似使用虚拟环境模式且关掉持久化Unity资源补丁支持就可能出现上图的问题。我最多见过三个崩3的预览窗口。

**Comment by Ph4n7om** [comment]
@xausky 这次“不修改”+持久化Unity资源补丁支持也出现了…😂
![screenshot_20180624-113928](https://user-images.githubusercontent.com/28192782/41815633-99b72d22-77a3-11e8-952d-76fbfc70c07d.png)

**Comment by xausky** [comment]
如果不修改也出现的话应该不使用管理器也会出现，不过这个也不太影响使用吧，启动的时候清一下之类

**Comment by Ph4n7om** [comment]
@xausky 不使用管理器从没出现过，如果出现了的话还是有点影响的，这在游戏中途是会出现的，要是点错了窗口会直接闪退。😂

**Comment by Ph4n7om** [comment]
@xausky 今天为了试着解决问题，删除后重装了管理器，结果屡次闪退，进都进不去了😭

**Comment by xausky** [comment]
不修改时快捷方式无效
