### ISSUE TITLE
模拟器下不响应鼠标滚轮事件。

### ISSUE THREAD

**Issue by szdkkk** [xausky/UnityModManager#32]
mumu模拟器，原生应用下响应鼠标滚轮，使用管理器之后不响应了。

**Comment by xausky** [comment]
游戏里面有需要滚轮的操作么？

**Comment by szdkkk** [comment]
有啊，材料，聊天很多界面都要滚动的。不支持的话只能按着鼠标拖，很累人的。

**Comment by xausky** [comment]
我试试

**Comment by xausky** [comment]
虚拟模式确实无法响应滚轮事件，不过模拟器一般有Root，直接使用Root模式就好。mumu推荐使用Root模式。

**Comment by xausky** [comment]
记得先用Lucky Patcher禁用ZIP签名验证

**Comment by szdkkk** [comment]
OK，我抽空试试
