### ISSUE TITLE
安卓9.0安装崩坏3客户端时显示无法解析安装包

### ISSUE THREAD

**Issue by pickmeup12345** [xausky/UnityModManager#33]
机型：pixel
安卓版本号：9.0.0 (PPR1.180610.009, Aug 2018)
模组和游戏客户端均为最新版本

手机直接安装的安卓官服在No Modify模式下调用没有异常
但是在Virtual App模式下无论安装手机上已安装的安卓官服还是只有apk包的ios版时均显示无法解析安装包（unable to parse the package）

怀疑跟google在9.0限制非 SDK 的接口的使用有关

**Comment by xausky** [comment]
这个等https://github.com/android-hacker/VirtualXposed这个项目那边解决吧，应该就是这个问题，不过他们已经在想办法解决了。
