### ISSUE TITLE
Failed to install mod

### ISSUE THREAD

**Issue by Aroruus** [xausky/UnityModManager#34]
Hello I am using the latest version. I want to mod honkai impact 3 sea and have obb option on. I keep getting failed to install mod

**Comment by xausky** [comment]
This problem is usually caused by incorrect module format. You can try to remove all modules and start them. If you can start, you can try to find the module in question.

**Comment by Aroruus** [comment]
I tried removing but it seems none are working for me

**Comment by xausky** [comment]
Clear data to reinstall the game directly to start this way too?

**Comment by Aroruus** [comment]
I did that too. Still get errlr

**Comment by xausky** [comment]
What is your device model and Android version?

**Comment by xausky** [comment]
Is your apk modification mode set to virtual mode? If it is Root mode, make sure you have root privileges.

**Comment by Aroruus** [comment]
It's not root mode

**Comment by xausky** [comment]
If the obb option is enabled, you need to ensure that the game obb file exists.
/sdcard/Android/obb/<package-name>/*.obb

**Comment by Aroruus** [comment]
I still keep getting keeping failed to install mods

**Comment by xausky** [comment]
Make sure that the obb file exists. If you don't exist, reinstalling the game from GooglePlay may solve the problem. Before using the module, make sure that you can enter the game normally, and then use the manager to install the game add mod.

**Comment by Aroruus** [comment]
I still keep getting failed to install mod. The obb is installed properly and so is the app

**Comment by Aroruus** [comment]
I found a solution. I downloaded the ingame files and then retried all steps and it worked

**Comment by Testdot-Jas** [comment]
> I found a solution. I downloaded the ingame files and then retried all steps and it worked

Hello, I know this has been closed but may I know how you had downloaded the ingame files?
