### ISSUE TITLE
android p 在管理器内无法安装崩崩崩

### ISSUE THREAD

**Issue by LexingtonHX** [xausky/UnityModManager#36]
管理器内安装就提示unable to parse the package，无法解析安装包
应该不是我个例，问了下me社群升了android p出现了同样的情况，请问下有办法解决这个问题吗？

**Comment by xausky** [comment]
android p 已经支持，欢迎测试

**Comment by LexingtonHX** [comment]
测试可以用了，玩了下暂未发现问题，感谢大佬
