### ISSUE TITLE
mumu用不了2.6了

### ISSUE THREAD

**Issue by LexingtonHX** [xausky/UnityModManager#37]
emmmm，这次是可以手机上android p安装崩崩崩了，但是mumu却用不了了。

mumu版本是1.19.2，android 4.4.4

是因为mumu的android版本太低了吗？

**Comment by xausky** [comment]
什么现象，我的mumu都升级6.0.1了啊，回不去了都

**Comment by LexingtonHX** [comment]
现象是无法打开，直接闪退

mumu的6.0版本太卡了，感知上就非常明显，所以我退回旧版了

**Comment by LexingtonHX** [comment]
补充下，是mod管理器打不开直接闪退

**Comment by xausky** [comment]
这个问题我周末看看能不能解决

**Comment by xausky** [comment]
由于VXP项目作者不打算修复这个问题，因为他的项目最低支持安卓5.0，你只能用2.5.2版本管理器或者升级mumu。
