### ISSUE TITLE
台服2.5更新問題

### ISSUE THREAD

**Issue by ProfessorHentai** [xausky/UnityModManager#38]
你好
本人是台服崩壞3玩家
自更新到2.5.0版本後
本人無法使用管理器打開崩壞3
( 每次打開會卡在miHoYo界面）

麻煩你提供協助,謝謝

**Comment by wingho0722** [comment]
我也是更新後，在mihoyo那裡卡著

**Comment by xausky** [comment]
台服是需要启用obb支持的是么？那样的话要确保使用虚拟环境模式。

**Comment by xausky** [comment]
可以参考这里的成功情况：#39
