### ISSUE TITLE
否能通过添加模组管理器功能做出模组版触摸反和谐

### ISSUE THREAD

**Issue by MyFaker** [xausky/UnityModManager#46]
现在触摸反和谐已经做出来[逆熵3rd贴吧精品帖](https://tieba.baidu.com/p/5982989014)，需要劫持官服更新地址下载加载反和谐资源，能否通过模组管理器支持达到直接加载触摸反和谐。

**Comment by naloder** [comment]
不建议使用这个方案。。

**Comment by xausky** [comment]
正在和反和谐的作者沟通，如果顺利近期会发布功能整合。

**Comment by naloder** [comment]
@xausky 这个我建议三思吧。。这个总感觉不太合适，官方没有默许这一类行为。。引起封号啥的就得不偿失了(๑• . •๑)

**Comment by xausky** [comment]
这个后面看，应该可以做成模组的形式，管理器只需要提供文件解析支持
