### ISSUE TITLE
Failed to open the app in NoxPlayer 6.2.6.3

### ISSUE THREAD

**Issue by cupuinside** [xausky/UnityModManager#47]
im using Unity Mod Manager 2.9. i successfully installed the app. but the app wont open and send me notification "unfortunately, unity mod manager has stopped". im using NoxPlayer 6.2.6.3. 

i also tried using the latest bluestack 4,it installed successfully and i can open it without problem. but whenever i play the game (pressing game pad icon on the top right) the app go into "Wait, in operation" and after awhile it goes into hang and the game don't start at all.

for information, my pc spec : intel core i5-4460, 3.2 Ghz(4 CPUs), 8 GB RAM, Nvidia GTX 750 Ti

**Comment by xausky** [comment]
I recommend using the mumu simulator, which is the only version of the simulator that has been tested for this project.
http://mumu.163.com/
