### ISSUE TITLE
MIUI10 Android9.0 崩溃

### ISSUE THREAD

**Issue by qq1198** [xausky/UnityModManager#48]
FATAL EXCEPTION: main
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               Process: io.github.xausky.unitymodmanager, PID: 2654
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.xausky.unitymodmanager/io.github.xausky.unitymodmanager.MainActivity}: com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2953)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3088)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1838)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:106)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.os.Looper.loop(Looper.java:201)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:6835)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               Caused by: com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at com.lody.virtual.client.env.VirtualRuntime.crash(VirtualRuntime.java:61)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at com.lody.virtual.client.core.VirtualCore.isOutsidePackageVisible(VirtualCore.java:394)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at io.github.xausky.unitymodmanager.adapter.VisibilityAdapter.update(VisibilityAdapter.java:68)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at io.github.xausky.unitymodmanager.adapter.VisibilityAdapter.<init>(VisibilityAdapter.java:48)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at io.github.xausky.unitymodmanager.fragment.VisibilityFragment.setBase(VisibilityFragment.java:40)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at io.github.xausky.unitymodmanager.fragment.BaseFragment.initialize(BaseFragment.java:46)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at io.github.xausky.unitymodmanager.MainActivity.onCreate(MainActivity.java:64)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.Activity.performCreate(Activity.java:7224)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.Activity.performCreate(Activity.java:7213)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               ... 11 more
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               Caused by: android.os.DeadObjectException
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.os.BinderProxy.transactNative(Native Method)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at android.os.BinderProxy.transact(Binder.java:1129)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at com.lody.virtual.server.IAppManager$Stub$Proxy.isOutsidePackageVisible(IAppManager.java:393)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               at com.lody.virtual.client.core.VirtualCore.isOutsidePackageVisible(VirtualCore.java:392)
03-16 10:08:23.071 2654 2654 E     AndroidRuntime                               ... 20 more

**Comment by xausky** [comment]
是否每次都稳定崩溃并且崩溃日志一样，如果是可以帮忙测试隔壁的项目么，本项目基于VXP：
https://github.com/android-hacker/VirtualXposed/releases

**Comment by qq1198** [comment]
@xausky 每次打开都是这个异常

**Comment by xausky** [comment]
@qq1198 可以帮忙测试上面那个项目么

**Comment by qq1198** [comment]
@xausky OK

**Comment by qq1198** [comment]
@xausky 不知道怎么回事。我这看不到日志，但是还是崩溃了

### io.va.exposed:
Not starting debugger since process cannot load the jdwp agent.

### DEBUG:
Fatal signal4( SIGILL), code1( ILL_ ILLOPC), fault addr0xf2c62534 in tid30905( Jit thread pool), pid30903( io. va. exposed)

**Comment by xausky** [comment]
你系统是内测版还是稳定版

**Comment by qq1198** [comment]
@xausky 管改包，可能是稳定版吧 米酒的

**Comment by xausky** [comment]
这个感觉是VXP项目就有这个问题

**Comment by qq1198** [comment]
@xausky 希望能解决下，麻烦你了谢谢

**Comment by naloder** [comment]
@xausky 要不去VXP项目底下问问。。_(:з」∠)_

**Comment by xausky** [comment]
@naloder 关键我也没有设备，不能确定是VXP的问题，到VXP搜索也没有发现有相关的issues

**Comment by xausky** [comment]
使用云测平台的云真机进行测试，没有问题，你的具体版本是什么 @qq1198 
MI 8
MIUI 10.2.2.0

**Comment by qq1198** [comment]
@xausky 我是Xiaomi 9 6+128G 星空包 稳定版MIUI10 9.3.5

**Comment by xausky** [comment]
@qq1198 你这个是非官方的定制ROM吧，感觉是这个的问题吧，兼容性测试报告也没有发现有什么问题：https://www.testin.cn/s/49bfcec7

**Comment by qq1198** [comment]
@xausky 不是官方的，有可能是系统问题吧

**Comment by xausky** [comment]
看日志是vxp的后台进程不存在，可能某些系统对后台进程限制太严启动不了或者被杀，你看看有没有白名单之类的，或者相关的设置。

**Comment by qq1198** [comment]
@xausky 我试了下还是崩溃，我把管控自启以及后台的都关了的

**Comment by qq1198** [comment]
@xausky 我将ROM刷到了官方的9.3.14开发版，依然会出现崩溃

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cepheus/cepheus:9/PKQ1.181121.001/9.3.14:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 32042, tid: 32047, name: Jit thread pool  >>> io.va.exposed:x <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb1187800
    r0  b1187800  r1  ecb574f4  r2  e6308000  r3  00000000
    r4  e6308000  r5  dff754b0  r6  ec2e1e5a  r7  706d6320
    r8  00000043  r9  ec332374  r10 ec333e9c  r11 0000005b
    ip  e65e78c8  sp  e65e78d0  lr  ec109767  pc  ec11d53c

backtrace:
    #00 pc 0026053c  /system/lib/libart.so (offset 0x254000) (art::ProfileSaver::NotifyJitActivity()+8)
    #01 pc 00007ffe  [anon:libc_malloc:e6300000]

**Comment by xausky** [comment]
vxp那边是表示只支持稳定版

**Comment by qq1198** [comment]
@xausky 那么能弄一个只保留root方式，不用虚拟的版本？

**Comment by naloder** [comment]
@xausky 我怀疑是mi9的虚拟机代码又被魔改过多了。。之前很多机型刚刚出来的时候不止vxp也有很多app直接崩溃打不开。。我这里是米8青春版安卓9.0正常使用。。

**Comment by xausky** [comment]
没有什么进展先关了，经过测试稳定版系统是可以的。
