### ISSUE TITLE
mumu模拟器无法正常导入mod

### ISSUE THREAD

**Issue by cherrysakurali** [xausky/UnityModManager#49]
映射文件数量与手机上不符，手机3w+，模拟器2.9w+
mod显示有效文件数量为0
请问是模拟器的问题吗？

**Comment by cherrysakurali** [comment]
刚尝试直接从模拟器自带浏览器下载mod，可以正常导入，而直接导入windows下已经下好的mod则还是数量为0

**Comment by xausky** [comment]
这种情况一般是mod自身的问题
