### ISSUE TITLE
小米9闪退

### ISSUE THREAD

**Issue by zhengchangsi** [xausky/UnityModManager#50]
系统：MIUI 10.2 稳定版 
手机：小米9 透明版 8+256 
问题：打开APP立即闪退 
其他：已经允许修改系统设置 读写手机存储 获取应用等

**Comment by cherrysakurali** [comment]
miui的锅，我红米note5，这两次更新之后跟你一样闪退

**Comment by xausky** [comment]
关于miui的问题已经反馈给上流vxp项目，可以到这里查看进度：https://github.com/android-hacker/VirtualXposed/issues/568

**Comment by xausky** [comment]
另外下版本将默认禁用虚拟模式来临时解决这个问题。

**Comment by naloder** [comment]
@xausky 预计何时发版?

**Comment by xausky** [comment]
已经发布 3.1.0 默认不启用虚拟模式，应该可以解决这个问题
