### ISSUE TITLE
miui10开发版，安9，闪退

### ISSUE THREAD

**Issue by cherrysakurali** [xausky/UnityModManager#51]
RT，开发版miui10，miui10 9.4.12开发版，安9内核
模组管理器打开就闪退。
前些日子还是安8.1的时候还好好的，升了安9就有问题

**Comment by naloder** [comment]
请报告机型

**Comment by cherrysakurali** [comment]
红米note5 4+64版 骁龙636

**Comment by cherrysakurali** [comment]
> 请报告机型
红米note5 4+64版 骁龙636

**Comment by xausky** [comment]
重复的问题 #50

**Comment by dxzm2013gmailcom** [comment]
我估计是miui10全机型不兼容吧建议作者下个版本增加一个抓包功能普通用户不会抓包啊
