### ISSUE TITLE
最新版本是否支持 unity3d 直接覆盖更换？

### ISSUE THREAD

**Issue by woeijiunn88** [xausky/UnityModManager#53]
有时候我想把 unity3d 文件压缩在一个包，
路径放置方式与 dat 文件压缩包相同，
然后点开开关直接执行更换，关闭开关恢复原文件。

所以想知道在 root模式/其他模式 下是否能这么做，
还是本身应用不支持此方式来替换文件？

**Comment by xausky** [comment]
支持unity3d直接覆盖替换但要注意下划线问题，比如要替换  
AsbStream/avatar/fh_dc_wdwdqdwq.unity3d
需要模组内文件名为全路径名去掉最后一个下划线和后面的部分，即  
AsbStream/avatar/fh_dc

**Comment by xausky** [comment]
可以参考这个，刚写：https://github.com/xausky/UnityModManager/wiki/%E6%A8%A1%E7%BB%84%E5%88%B6%E4%BD%9C%E6%8C%87%E5%BC%95

**Comment by woeijiunn88** [comment]
好的 之后的空的话试看

**Comment by fatinghenji** [comment]
3.2貌似不行了。我尝试按照wiki的方法进行操作，但是依旧是映射为0。希望大佬可以给出一个更加详细的wiki。可以加入新旧mod的修补方法之类的
