### ISSUE TITLE
MuMu 2.04版本改不了MOD 也是Android6.0的内核，映射数量只有6

### ISSUE THREAD

**Issue by xiaoxin7534** [xausky/UnityModManager#54]
![微信截图_20190505113326](https://user-images.githubusercontent.com/19758918/57187974-a8eda680-6f29-11e9-9fd2-317bdc747d86.png)
![微信截图_20190505113444](https://user-images.githubusercontent.com/19758918/57187983-d20e3700-6f29-11e9-8761-718e1bad1575.png)
新版本的MUMU实在是不好用。。。但是老版本流畅却不能改MOD。再升上去就是新版本了很蛋疼

**Comment by xausky** [comment]
你要先进游戏下载资源完了再点生成映射

**Comment by xiaoxin7534** [comment]
资源都是下载完的～其实从上个版本就不行了，上个版本用mumu2.04映射是21个，用mumu的最新版本就没问题。要么就是这版本mumu有问题…因为安卓4.4根本装不上模组管理器～

**Comment by xausky** [comment]
@xiaoxin7534 检查设置里面开启持久化资源支持

**Comment by xiaoxin7534** [comment]
这个应该是不行了，和3.0的时候一样~
![微信截图_20190505175942](https://user-images.githubusercontent.com/19758918/57192134-b0c83d80-6f5f-11e9-9283-f01960b7b728.png)
![微信截图_20190505175958](https://user-images.githubusercontent.com/19758918/57192135-b0c83d80-6f5f-11e9-8ee6-76a4f26312e9.png)
![微信截图_20190505180008](https://user-images.githubusercontent.com/19758918/57192136-b160d400-6f5f-11e9-9d56-ca180b8bfbf4.png)

@xausky

**Comment by xausky** [comment]
APK修改方式是不修改么

**Comment by xiaoxin7534** [comment]
我的设置都对的。我升级最新的mumu是可以用的。我现在问题的就是最新的mumu确实不太好用（各种爆音掉帧也不知道为什么），所以才向大佬来求助了~我上最新版本mumu改MOD成功的图~天火自裁
![TIM截图20190506152159](https://user-images.githubusercontent.com/19758918/57211396-b468cc80-7012-11e9-9908-4fe9430fafff.png)

**Comment by xausky** [comment]
应该是只要6.0版本的mumu都是支持的，你这个情况估计也是哪里出现问题，你可以清除数据重新尝试，然后新版本mumu也没有那么多问题，可能是配置有点问题，我一直用最新版的。
