### ISSUE TITLE
持久化资源支持是否可以不覆盖游戏原始文件

### ISSUE THREAD

**Issue by nyfair** [xausky/UnityModManager#56]
测试自己制作的模组的时候，发现启用时会直接使用模组内的文件替换游戏原始路径下的文件，有没有可能做到不改动原始文件或者自动备份原始文件，谢谢

**Comment by xausky** [comment]
现在会自动备份原文件，只需要关闭所有模组启动一次游戏就还原了，也可以使用游戏内的资源修复功能还原。
