### ISSUE TITLE
me社群那边的建议(或许会不定期发过来。)

### ISSUE THREAD

**Issue by naloder** [xausky/UnityModManager#9]
- [x] 批量导入mod(或者读取某一文件夹下的所有mod之类的)，然后根据重复或者需要合并或者删减。
- [x] 对root模式进行优化，对魔改包能兼容好一些
- [x] 能像vamod一样有保留后台等优化功能，有些特殊系统杀后台严重 
- [x] 对模组列表加入分割线，或者每个mod背景做些颜色区别。在模拟器等非手机设备等显示有些不容易辨别 
- [x] 渠道服有啥特殊要求吗?

**Comment by xausky** [comment]
批量导入功能下版本将实现。

**Comment by xausky** [comment]
我考虑移除root模式了，因为发现root模式修改apk后，重启机器可能导致应用消失，而且现在root的人越来越少，打算全力支持虚拟模式。
关于保活功能的话可能要咨询一下vamod的作者，不知道是否只是显示一个通知来防止被系统杀掉。

**Comment by xausky** [comment]
渠道服我自己只测试了应用宝服，需要添加QQ到附加组件里面

**Comment by xausky** [comment]
模组列表UI优化会在下版本发表前搞一下。

**Comment by xausky** [comment]
我帮你改了一下表示已回答的列表显示方法，这样，我回答完问题我就关闭issue，然后你有新问题就重新打开这个issue，这样我就会收到通知，不需要每次都重新开应该issue来提醒我。
